In [2]:
import numpy as np
from scipy.optimize import minimize
a = np.matrix('3 1; 1 -2') 
b = np.matrix('1;0')
U = np.matrix('1 0;0 1')
zKet = np.matrix('1;0')


#calculate cost
def calculate_cost(alpha, alpha2):
    V = np.matrix([[np.cos(alpha/2.), -1*np.sin(alpha/2.)], [np.sin(alpha/2.), np.cos(alpha/2.)]])*z*np.matrix([[np.cos(alpha2/2.), -1*np.sin(alpha2/2.)], [np.sin(alpha2/2.), np.cos(alpha2/2.)]])
    param1 = 0
    for i in range (0, len(a)):
        param1 += c[i]*np.transpose(zKet)@np.transpose(U)@a[i]@V@zKet
    param1 = param1 **2
    param2 = 0
    for i in range (0, len(a)):
        param2 += c[i]*c[i] * np.transpose(zKet) * np.transpose(V) * np.transpose(a[i]) * a[i] * V * zKet
    #param2 = np.matmul(np.matmul(np.matmul(np.matmul(np.matmul(np.transpose(zKet),np.transpose(V)),np.transpose(a)),a),V),zKet)
    cost = 1 - (param1/param2)
    cost = np.asarray(cost)
    cost = cost[0][0]
    print("cost = " + str(cost) + " for alpha1 = " + str(alpha))
    return cost

def optimize(alpha):
    dV = np.matrix([[-1*np.sin(alpha/2.), -1*np.cos(alpha/2.)], [np.cos(alpha/2.), -1*np.cos(alpha/2.)]])
    V = np.matrix([[np.cos(alpha/2.), -1*np.sin(alpha/2.)], [np.sin(alpha/2.), np.cos(alpha/2.)]])
    for i in range (0, len(a)):
        f = c[i]*np.transpose(zKet)*np.transpose(U)*a[i]*V*zKet
    f *= f
    for i in range (0, len(a)):
        g = c[i]*c[i]*np.transpose(zKet)*np.transpose(V)*np.transpose(a[i])*a[i]*V*zKet
        fp = c[i]*c[i]*np.transpose(zKet)*np.transpose(U)*a[i]*dV*zKet*np.transpose(zKet)*np.transpose(V)*np.transpose(a[i])*V*zKet + c[i]*c[i]*np.transpose(zKet)*np.transpose(U)*a[i]*V*zKet*np.transpose(zKet)*np.transpose(dV)*np.transpose(a[i])*V*zKet
        gp = c[i]*c[i]*np.transpose(zKet)*np.transpose(dV)*np.transpose(a[i])*a[i]*V*zKet + c[i]*c[i]*np.transpose(zKet)*np.transpose(V)*np.transpose(a[i])*a[i]*dV*zKet
    dCost = -1*((fp*g - f*gp)/(g*g))
    newAlpha1 = alpha + lr*dCost
    newAlpha1 = np.asarray(newAlpha1)[0][0]
    return newAlpha1;
alpha = np.pi/3;

cost = calculate_cost(alpha)
maxiter = 100000
iters = 0 
threshold = 0.000163
while((abs(cost) > threshold) and (maxiter > iters)):
    #print('##################################ITERATION - '+ str(iters) +'  ###############################')
    alpha = optimize(alpha)
    cost = calculate_cost(alpha)
    #print('##################################  END   ###############################\n')
    iters +=1
print(alpha)
alpha = 1.6901249977459203
V = np.matrix([[np.cos(alpha/2.), -1*np.sin(alpha/2.)], [np.sin(alpha/2.), np.cos(alpha/2.)]])
print (V*zKet)

TypeError: calculate_cost() missing 1 required positional argument: 'alpha2'

In [8]:
a = 1+2j
abs(a)

2.23606797749979

In [4]:
import numpy as np
from scipy.optimize import minimize
import math
a = np.matrix('3 1; 1 -2') 
#a = a/10
print(np.linalg.norm(a))
print(np.linalg.cond(a))
b = np.matrix('1;0')
U = np.matrix('1 1;1 -1')*(1/(math.sqrt(2)))
#U = U/10
z = np.matrix('1 0;0 -1')
zKet = np.matrix('1;0')
lr = 0.001
ans = np.asmatrix('0.303043;  -0.202029')
print((ans)/np.linalg.norm(ans))
#calculate cost
def calculate_cost(alpha, alpha2):
    V = np.matrix([[np.cos(alpha/2.), -1*np.sin(alpha/2.)], [np.sin(alpha/2.), np.cos(alpha/2.)]])*z*np.matrix([[np.cos(alpha2/2.), -1*np.sin(alpha2/2.)], [np.sin(alpha2/2.), np.cos(alpha2/2.)]])

    param1 = 0
    param1 += np.transpose(zKet)@np.transpose(U)@a@V@zKet
    param1 = param1**2
    param2 = 0
    param2 = np.transpose(zKet) * np.transpose(V) * np.transpose(a) * a * V * zKet
    #print("param2 "+str(param2))
    #param2 = np.matmul(np.matmul(np.matmul(np.matmul(np.matmul(np.transpose(zKet),np.transpose(V)),np.transpose(a)),a),V),zKet)
    cost = 1 - (param1/param2)
    cost = np.asarray(cost)
    cost = cost[0][0]
    #print("cost = " + str(cost) + " for alpha1 = " + str(alpha))
    return cost

def optimize(alpha, alpha2):
    dV = np.matrix([[-1*np.sin(alpha/2.), -1*np.cos(alpha/2.)], [np.cos(alpha/2.), -1*np.cos(alpha/2.)]])*z*np.matrix([[np.cos(alpha2/2.), -1*np.sin(alpha2/2.)], [np.sin(alpha2/2.), np.cos(alpha2/2.)]])
    V = np.matrix([[np.cos(alpha/2.), -1*np.sin(alpha/2.)], [np.sin(alpha/2.), np.cos(alpha/2.)]])*z*np.matrix([[np.cos(alpha2/2.), -1*np.sin(alpha2/2.)], [np.sin(alpha2/2.), np.cos(alpha2/2.)]])
    f = np.transpose(zKet)*np.transpose(U)*a*V*zKet
    f *= f
    g = np.transpose(zKet)*np.transpose(V)*np.transpose(a)*a*V*zKet
    fp = np.transpose(zKet)*np.transpose(U)*a*dV*zKet*np.transpose(zKet)*np.transpose(V)*np.transpose(a)*V*zKet + np.transpose(zKet)*np.transpose(U)*a*V*zKet*np.transpose(zKet)*np.transpose(dV)*np.transpose(a)*V*zKet
    gp = np.transpose(zKet)*np.transpose(dV)*np.transpose(a)*a*V*zKet + np.transpose(zKet)*np.transpose(V)*np.transpose(a)*a*dV*zKet
    dCost = -1*((fp*g - f*gp)/(g*g))
    newAlpha1 = alpha - lr*dCost
    newAlpha1 = np.asarray(newAlpha1)[0][0]
    dV = np.matrix([[-1*np.sin(alpha2/2.), -1*np.cos(alpha2/2.)], [np.cos(alpha2/2.), -1*np.cos(alpha2/2.)]])*z*np.matrix([[np.cos(alpha/2.), -1*np.sin(alpha/2.)], [np.sin(alpha/2.), np.cos(alpha/2.)]])
    f = np.transpose(zKet)*np.transpose(U)*a*V*zKet
    f *= f
    g = np.transpose(zKet)*np.transpose(V)*np.transpose(a)*a*V*zKet
    fp = np.transpose(zKet)*np.transpose(U)*a*dV*zKet*np.transpose(zKet)*np.transpose(V)*np.transpose(a)*V*zKet + np.transpose(zKet)*np.transpose(U)*a*V*zKet*np.transpose(zKet)*np.transpose(dV)*np.transpose(a)*V*zKet
    gp = np.transpose(zKet)*np.transpose(dV)*np.transpose(a)*a*V*zKet + np.transpose(zKet)*np.transpose(V)*np.transpose(a)*a*dV*zKet
    dCost = -1*((fp*g - f*gp)/(g*g))
    newAlpha2 = alpha2 - lr*dCost
    newAlpha2 = np.asarray(newAlpha2)[0][0]
    #print(newAlpha)
    return newAlpha1, newAlpha2;
alpha = np.pi/4;
alpha1 = np.pi/3;
cost = calculate_cost(alpha, alpha1)
maxiter = 20000
iters = 0 
threshold = 0.000000047
while((abs(cost) > threshold) and (maxiter > iters)):
    #print('##################################ITERATION - '+ str(iters) +'  ###############################')
    alpha, alpha1 = optimize(alpha, alpha1)
    cost = calculate_cost(alpha, alpha1)
    #print('##################################  END   ###############################\n')
    iters +=1
print(cost)
print(alpha,alpha1)
print(iters)
alpha2 = alpha1
V = np.matrix([[np.cos(alpha/2.), -1*np.sin(alpha/2.)], [np.sin(alpha/2.), np.cos(alpha/2.)]])*z*np.matrix([[np.cos(alpha2/2.), -1*np.sin(alpha2/2.)], [np.sin(alpha2/2.), np.cos(alpha2/2.)]])
print (V*zKet)

3.872983346207417
1.4560832005096072
[[ 0.83204987]
 [-0.55470083]]
4.873403902649898e-09
2.109859313179849 3.2857141567413395
8368
[[ 0.832092  ]
 [-0.55463764]]


In [3]:
import numpy as np
from scipy.optimize import minimize
import math
a = np.asmatrix('1+2j 1+3j 1 1;2+2j 3 4+3j 5; 5+1j 0 4 0; 3 1-2j 0 0-9j') 
#a = a/np.linalg.norm(a)
#a = a/10
I = np.asmatrix('1 0;0 1')
X = np.asmatrix('0 1;1 0')
Y = np.asmatrix('0 0-1j;0+1j 0')
Z = np.asmatrix('1 0;0 -1')
HP = X+Y
zKet = np.asmatrix('1;0')
H = (1/math.sqrt(2))*np.asmatrix('1 1;1 -1')
U = np.asmatrix('5 6 7+1j 8; 1 3 4 5; 6 7 8 9; 3 5 11 1')
U = U/np.linalg.norm(a)
a = a/np.linalg.norm(a)
U = U
a = a
#U = U/10
zKet = np.kron(zKet,zKet)
lr = 0.001
#print(U)
ans = np.linalg.inv(a)*U*zKet
print((ans)/np.linalg.norm(ans))
z = np.asmatrix('1 0 0 0; 0 1 0 0; 0 0 1 0; 0 0 0 -1')
y = np.kron(Z,Z)
print(y)
#calculate cost
def calculate_cost(params):
    alpha = params[0]
    alpha2 = params[1]
    alpha3 = params[2]
    alpha4 = params[3]
    Ry1 = np.matrix([[np.cos(alpha/2.), -1*np.sin(alpha/2.)], [np.sin(alpha/2.), np.cos(alpha/2.)]])
    Ry2 = np.matrix([[np.cos(alpha3/2.), -1*np.sin(alpha3/2.)], [np.sin(alpha3/2.), np.cos(alpha3/2.)]])
    Ry = np.kron(Ry1,Ry2)
    Ry3 = np.matrix([[np.cos(alpha2/2.), -1j*np.sin(alpha2/2.)], [-1j*np.sin(alpha2/2.), np.cos(alpha2/2.)]])
    Ry4 = np.matrix([[np.cos(alpha4/2.), -1j*np.sin(alpha4/2.)], [-1j*np.sin(alpha4/2.), np.cos(alpha4/2.)]])
    Ry5 = np.kron(Ry3,Ry4)
    V = Ry*y*Ry5

    param1 = 0
    param1 += np.transpose(zKet)@np.transpose(U)@a@V@zKet
    param1 = param1**2
    param2 = 0
    param2 = np.transpose(zKet) * np.transpose(V) * np.transpose(a) * a * V * zKet
    #print("param2 "+str(param2))
    #param2 = np.matmul(np.matmul(np.matmul(np.matmul(np.matmul(np.transpose(zKet),np.transpose(V)),np.transpose(a)),a),V),zKet)
    cost = 1 - (param1/param2)
    cost = np.asarray(cost)
    cost = cost[0][0]
    #print("cost = " + str(cost) + " for alpha1 = " + str(alpha))
    return abs(cost)+ abs(np.angle(cost))


maxiter = 2000000
iters = 0 
threshold = 0.0000000000047
'''while((abs(cost) > threshold) and (maxiter > iters)):
    #print('##################################ITERATION - '+ str(iters) +'  ###############################')
    alpha, alpha1 = optimize(alpha, alpha1)
    cost = calculate_cost(alpha, alpha1)
    #print('##################################  END   ###############################\n')
    iters +=1
print(cost)
print(alpha,alpha1)
print(iters)
alpha2 = alpha1'''
from scipy.optimize import minimize
init_params = [np.pi/32, np.pi/32, np.pi/2, np.pi/16]
print(init_params)
calculate_cost(init_params)

out = minimize(calculate_cost, x0=init_params, method="COBYLA", options= {'maxiter':2000, 'disp': True}, tol = threshold)
print(out)
alpha = out['x'][0]
alpha2 = out['x'][1]
alpha3 = out['x'][2]
alpha4 = out['x'][3]
Ry1 = np.matrix([[np.cos(alpha/2.), -1*np.sin(alpha/2.)], [np.sin(alpha/2.), np.cos(alpha/2.)]])
Ry2 = np.matrix([[np.cos(alpha3/2.), -1*np.sin(alpha3/2.)], [np.sin(alpha3/2.), np.cos(alpha3/2.)]])
Ry = np.kron(Ry1,Ry2)
Ry3 = np.matrix([[np.cos(alpha2/2.), -1j*np.sin(alpha2/2.)], [-1j*np.sin(alpha2/2.), np.cos(alpha2/2.)]])
Ry4 = np.matrix([[np.cos(alpha4/2.), -1j*np.sin(alpha4/2.)], [-1j*np.sin(alpha4/2.), np.cos(alpha4/2.)]])
Ry5 = np.kron(Ry3,Ry4)
V = Ry*y*Ry5
print (V*zKet)


[[ 0.61069234-0.17236544j]
 [-0.18753012-0.71881555j]
 [ 0.06021441+0.06278371j]
 [-0.09565018+0.16960295j]]
[[ 1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0 -1  0]
 [ 0  0  0  1]]
[0.09817477042468103, 0.09817477042468103, 1.5707963267948966, 0.19634954084936207]
     fun: 0.3935630769474573
   maxcv: 0.0
 message: 'Optimization terminated successfully.'
    nfev: 184
  status: 1
 success: True
       x: array([ 0.22898668,  1.25027067,  1.72801043, -0.06557915])
[[0.5245234 -0.02330949j]
 [0.61084651-0.0679637j ]
 [0.04563267+0.37965005j]
 [0.08278602+0.43989695j]]


In [36]:
import numpy as np
from scipy.optimize import minimize
import math
a = np.asmatrix('11.5384615384615 -4.80769230769231 2.17948717948718 -0.961538461538462;-4.80769230769231 8.84615384615385 -0.961538461538462 1.69230769230769;-2.30769230769231 0.961538461538462 10.8974358974359 -4.80769230769231;0.961538461538462 -1.76923076923077 -4.80769230769231 8.46153846153846') 
#a = a/np.linalg.norm(a)
#a = a/10
I = np.asmatrix('1 0;0 1')
X = np.asmatrix('0 1;1 0')
Y = np.asmatrix('0 0-1j;0+1j 0')
Z = np.asmatrix('1 0;0 -1')
zKet = np.asmatrix('-0.535897435897435;-0.211538461538460;0.0205128205128212;0.0923076923076916') #np.asmatrix('1;0')
H = (1/math.sqrt(2))*np.asmatrix('1 1;1 -1')
U = np.kron(I,I)#np.asmatrix('-0.535897435897435;-0.211538461538460;0.0205128205128212;0.0923076923076916')
#U = U/np.linalg.norm(a)
#a = a/np.linalg.norm(a)
U = U/100
a = a/100
#U = U/10
#zKet = np.kron(zKet,zKet)
print(U*zKet)
lr = 0.001
#print(U)
ans = np.linalg.inv(a)*U*zKet
print((ans)/np.linalg.norm(ans))
z = np.asmatrix('1 0 0 0; 0 1 0 0; 0 0 1 0; 0 0 0 -1')
#calculate cost
def calculate_cost(params):
    alpha = params[0]
    alpha2 = params[1]
    alpha3 = params[2]
    alpha4 = params[3]
    Ry1 = np.matrix([[np.cos(alpha/2.), -1*np.sin(alpha/2.)], [np.sin(alpha/2.), np.cos(alpha/2.)]])
    Ry2 = np.matrix([[np.cos(alpha3/2.), -1*np.sin(alpha3/2.)], [np.sin(alpha3/2.), np.cos(alpha3/2.)]])
    Ry = np.kron(Ry1,Ry2)
    Ry3 = np.matrix([[np.cos(alpha2/2.), -1*np.sin(alpha2/2.)], [np.sin(alpha2/2.), np.cos(alpha2/2.)]])
    Ry4 = np.matrix([[np.cos(alpha4/2.), -1*np.sin(alpha4/2.)], [np.sin(alpha4/2.), np.cos(alpha4/2.)]])
    Ry5 = np.kron(Ry3,Ry4)
    V = Ry*z*Ry5

    param1 = 0
    param1 += np.transpose(zKet)@np.transpose(U)@a@V@zKet
    param1 = param1**2
    param2 = 0
    param2 = np.transpose(zKet) * np.transpose(V) * np.transpose(a) * a * V * zKet
    #print("param2 "+str(param2))
    #param2 = np.matmul(np.matmul(np.matmul(np.matmul(np.matmul(np.transpose(zKet),np.transpose(V)),np.transpose(a)),a),V),zKet)
    cost = 1 - (param1/param2)
    cost = np.asarray(cost)
    cost = cost[0][0]
    #print("cost = " + str(cost) + " for alpha1 = " + str(alpha))
    return abs(cost)


maxiter = 2000000
iters = 0 
threshold = 0.00000000000047
'''while((abs(cost) > threshold) and (maxiter > iters)):
    #print('##################################ITERATION - '+ str(iters) +'  ###############################')
    alpha, alpha1 = optimize(alpha, alpha1)
    cost = calculate_cost(alpha, alpha1)
    #print('##################################  END   ###############################\n')
    iters +=1
print(cost)
print(alpha,alpha1)
print(iters)
alpha2 = alpha1'''
from scipy.optimize import minimize
init_params = [np.pi/8, np.pi/4, np.pi/2, np.pi/16]
print(init_params)
calculate_cost(init_params)
out = minimize(calculate_cost, x0=init_params, method="COBYLA", options= {'maxiter':2000, 'disp': True}, tol = threshold)
print(out)
alpha = out['x'][0]
alpha2 = out['x'][1]
alpha3 = out['x'][2]
alpha4 = out['x'][3]
Ry1 = np.matrix([[np.cos(alpha/2.), -1*np.sin(alpha/2.)], [np.sin(alpha/2.), np.cos(alpha/2.)]])
Ry2 = np.matrix([[np.cos(alpha3/2.), -1*np.sin(alpha3/2.)], [np.sin(alpha3/2.), np.cos(alpha3/2.)]])
Ry = np.kron(Ry1,Ry2)
Ry3 = np.matrix([[np.cos(alpha2/2.), -1*np.sin(alpha2/2.)], [np.sin(alpha2/2.), np.cos(alpha2/2.)]])
Ry4 = np.matrix([[np.cos(alpha4/2.), -1*np.sin(alpha4/2.)], [np.sin(alpha4/2.), np.cos(alpha4/2.)]])
Ry5 = np.kron(Ry3,Ry4)
V = Ry*z*Ry5
print (V*zKet)


[[-0.00535897]
 [-0.00211538]
 [ 0.00020513]
 [ 0.00092308]]
[[-0.74406453]
 [-0.66403928]
 [-0.07124916]
 [ 0.01853034]]
[0.39269908169872414, 0.7853981633974483, 1.5707963267948966, 0.19634954084936207]
     fun: 0.9999659123931628
   maxcv: 0.0
 message: 'Optimization terminated successfully.'
    nfev: 310
  status: 1
 success: True
       x: array([0.3266539 , 0.13430515, 3.28968543, 3.6605477 ])
[[ 0.43441898]
 [ 0.38769662]
 [ 0.04159989]
 [-0.01081672]]


In [40]:
import numpy as np
from scipy.optimize import minimize
import math
#a = np.matrix('11.5384615384615,-4.80769230769231,2.17948717948718,-0.961538461538462;-4.80769230769231,8.84615384615385,-0.961538461538462,1.69230769230769;-2.30769230769231,0.961538461538462,10.8974358974359,-4.80769230769231;0.961538461538462,-1.76923076923077,-4.80769230769231,8.46153846153846')
a  = np.matrix('1 2 3 4; 5 6 7 8; 9 10 11 12; 13 14 15 16')
print(a)
#a = a/np.linalg.norm(a)
#a = a/10
I = np.asmatrix('1 0;0 1')
X = np.asmatrix('0 1;1 0')
Y = np.asmatrix('0 0-1j;0+1j 0')
Z = np.asmatrix('1 0;0 -1')
zKet = np.asmatrix('1;0') #np.asmatrix('1;0')
H = (1/math.sqrt(2))*np.asmatrix('1 1;1 -1')
U = np.asmatrix('-0.535897435897435, 0, 0, 0;-0.211538461538460, -0.211538461538460, 0, 0;0.0205128205128212, 0, 0.0205128205128212, 0;0.0923076923076916, 0, 0, 0.0923076923076916')
#U = U/np.linalg.norm(a)
#a = a/np.linalg.norm(a)
U = U/1000
a = a/1000
#U = U/10
zKet = np.kron(zKet,zKet)
print(U*zKet)
lr = 0.001
#print(U)
ans = np.linalg.inv(a)*U*zKet
print((ans)/np.linalg.norm(ans))
z = np.asmatrix('1 0 0 0; 0 1 0 0; 0 0 1 0; 0 0 0 -1')
#z = np.kron(Z,Z)
#calculate cost
def calculate_cost(params):
    alpha = params[0]
    alpha2 = params[2]
    alpha3 = params[1]
    alpha4 = params[3]
    Ry1 = np.matrix([[np.cos(alpha/2.), -1*np.sin(alpha/2.)], [np.sin(alpha/2.), np.cos(alpha/2.)]])
    Ry2 = np.matrix([[np.cos(alpha3/2.), -1*np.sin(alpha3/2.)], [np.sin(alpha3/2.), np.cos(alpha3/2.)]])
    Ry = np.kron(Ry1,Ry2)
    Ry3 = np.matrix([[np.cos(alpha2/2.), -1*np.sin(alpha2/2.)], [np.sin(alpha2/2.), np.cos(alpha2/2.)]])
    Ry4 = np.matrix([[np.cos(alpha4/2.), -1*np.sin(alpha4/2.)], [np.sin(alpha4/2.), np.cos(alpha4/2.)]])
    Ry5 = np.kron(Ry3,Ry4)
    V = Ry5*z*Ry

    param1 = 0
    param1 += np.transpose(zKet)@np.transpose(U)@a@V@zKet
    param1 = param1**2
    param2 = 0
    param2 = np.transpose(zKet) * np.transpose(V) * np.transpose(a) * a * V * zKet
    #print("param2 "+str(param2))
    #param2 = np.matmul(np.matmul(np.matmul(np.matmul(np.matmul(np.transpose(zKet),np.transpose(V)),np.transpose(a)),a),V),zKet)
    cost = 1 - (param1/param2)
    cost = np.asarray(cost)
    cost = cost[0][0]
    #print("cost = " + str(cost) + " for alpha1 = " + str(alpha))
    return abs(cost)


'''alpha = np.pi/6;
alpha1 = np.pi/8;
cost = calculate_cost(alpha, alpha1)'''
maxiter = 2000000
iters = 0 
threshold = 0.00000000000047
'''while((abs(cost) > threshold) and (maxiter > iters)):
    #print('##################################ITERATION - '+ str(iters) +'  ###############################')
    alpha, alpha1 = optimize(alpha, alpha1)
    cost = calculate_cost(alpha, alpha1)
    #print('##################################  END   ###############################\n')
    iters +=1
print(cost)
print(alpha,alpha1)
print(iters)
alpha2 = alpha1'''
from scipy.optimize import minimize
init_params = [np.pi/8, np.pi/4, np.pi/2, np.pi/16]
print(init_params)
calculate_cost(init_params)
out = minimize(calculate_cost, x0=init_params, method="cobyla", options= {'maxiter':20000, 'disp': True}, tol = threshold)
print(out)
alpha = out['x'][0]
alpha2 = out['x'][2]
alpha3 = out['x'][1]
alpha4 = out['x'][3]
Ry1 = np.matrix([[np.cos(alpha/2.), -1*np.sin(alpha/2.)], [np.sin(alpha/2.), np.cos(alpha/2.)]])
Ry2 = np.matrix([[np.cos(alpha3/2.), -1*np.sin(alpha3/2.)], [np.sin(alpha3/2.), np.cos(alpha3/2.)]])
Ry = np.kron(Ry1,Ry2)
Ry3 = np.matrix([[np.cos(alpha2/2.), -1*np.sin(alpha2/2.)], [np.sin(alpha2/2.), np.cos(alpha2/2.)]])
Ry4 = np.matrix([[np.cos(alpha4/2.), -1*np.sin(alpha4/2.)], [np.sin(alpha4/2.), np.cos(alpha4/2.)]])
Ry5 = np.kron(Ry3,Ry4)
V = Ry5*z*Ry
print (V*zKet)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[-5.35897436e-04]
 [-2.11538462e-04]
 [ 2.05128205e-05]
 [ 9.23076923e-05]]
[[-0.52691882]
 [ 0.81400487]
 [-0.04725329]
 [-0.23983276]]
[0.39269908169872414, 0.7853981633974483, 1.5707963267948966, 0.19634954084936207]
     fun: 0.9999996753019396
   maxcv: 0.0
 message: 'Optimization terminated successfully.'
    nfev: 98
  status: 1
 success: True
       x: array([1.56110726, 0.68371289, 3.22628311, 1.92881442])
[[-0.57901122]
 [-0.43898241]
 [ 0.16140602]
 [ 0.66782374]]


In [21]:
a = np.matrix('1 2 3 4; 2 5 1 3; 3 1 6 2; 4 3 2 7')
s, e, v = np.linalg.svd(a)
e_n = np.eye(e.shape[0])
for i in range(e.shape[0]):
    e_n[i][i] = e[i]
e_n = np.asmatrix(e_n)
e_n

matrix([[12.72601392,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  4.97261471,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  2.82725283,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.52588146]])

In [7]:
def is_unitary(m):
    return np.allclose(np.eye(m.shape[0]), m.H * m)

In [22]:
is_unitary(s*v)

True

In [3]:
import numpy as np
from scipy.optimize import minimize
import math
a = np.matrix('1 2 3 4; 2 5 1 3; 3 1 6 2; 4 3 2 7')
#a = a/np.linalg.norm(a)
#a = a/10
I = np.asmatrix('1 0;0 1')
X = np.asmatrix('0 1;1 0')
Y = np.asmatrix('0 0-1j;0+1j 0')
Z = np.asmatrix('1 0;0 -1')

a = 2*Z + 0.5*X
zKet = np.asmatrix('1;0') #np.asmatrix('1;0')
H = (1/math.sqrt(2))*np.asmatrix('1 1;1 -1')
U = H
#U = U/np.linalg.norm(a)
#a = a/np.linalg.norm(a)
U = U/10
a = a/10
#U = U/10
#zKet = np.kron(zKet,zKet)
print(U*zKet)
lr = 0.001
#print(U)
ans = np.linalg.inv(a)*U*zKet
print((ans)/np.linalg.norm(ans))
z = Z
#calculate cost
def calculate_cost(params):
    alpha = params[0]
    alpha4 = params[1]
    Ry1 = np.matrix([[np.cos(alpha/2.), -1*np.sin(alpha/2.)], [np.sin(alpha/2.), np.cos(alpha/2.)]])
    Ry4 = np.matrix([[np.cos(alpha4/2.), -1*np.sin(alpha4/2.)], [np.sin(alpha4/2.), np.cos(alpha4/2.)]])
    
    V = Ry1*z*Ry4

    param1 = 0
    param1 += np.transpose(zKet)@np.transpose(U)@a@V@zKet
    param1 = param1**2
    param2 = 0
    param2 = np.transpose(zKet) * np.transpose(V) * np.transpose(a) * a * V * zKet
    #print("param2 "+str(param2))
    #param2 = np.matmul(np.matmul(np.matmul(np.matmul(np.matmul(np.transpose(zKet),np.transpose(V)),np.transpose(a)),a),V),zKet)
    cost = 1 - (param1/param2)
    cost = np.asarray(cost)
    cost = cost[0][0]
    #print("cost = " + str(cost) + " for alpha1 = " + str(alpha))
    return abs(cost)


'''alpha = np.pi/6;
alpha1 = np.pi/8;
cost = calculate_cost(alpha, alpha1)'''
maxiter = 2000000
iters = 0 
threshold = 0.00000000000047
'''while((abs(cost) > threshold) and (maxiter > iters)):
    #print('##################################ITERATION - '+ str(iters) +'  ###############################')
    alpha, alpha1 = optimize(alpha, alpha1)
    cost = calculate_cost(alpha, alpha1)
    #print('##################################  END   ###############################\n')
    iters +=1
print(cost)
print(alpha,alpha1)
print(iters)
alpha2 = alpha1'''
from scipy.optimize import minimize
init_params = [np.pi/8, np.pi/4]
print(init_params)
calculate_cost(init_params)
out = minimize(calculate_cost, x0=init_params, method="COBYLA", options= {'maxiter':20000, 'disp': True}, tol = threshold)
print(out)
alpha = out['x'][0]
alpha4 = out['x'][1]
Ry1 = np.matrix([[np.cos(alpha/2.), -1*np.sin(alpha/2.)], [np.sin(alpha/2.), np.cos(alpha/2.)]])
Ry4 = np.matrix([[np.cos(alpha4/2.), -1*np.sin(alpha4/2.)], [np.sin(alpha4/2.), np.cos(alpha4/2.)]])
    
V = Ry1*z*Ry4
print (V*zKet)


[[0.07071068]
 [0.07071068]]
[[ 0.85749293]
 [-0.51449576]]
[0.39269908169872414, 0.7853981633974483]
     fun: 0.99
   maxcv: 0.0
 message: 'Optimization terminated successfully.'
    nfev: 62
  status: 1
 success: True
       x: array([1.11828132, 2.19912033])
[[ 0.85749292]
 [-0.51449576]]


In [7]:
a = np.matrix('1 2 3 4; 2 5 1 3; 3 1 6 2; 4 3 2 7')
U = np.asmatrix('0.7071 0 0 0;0.7071 0.7071 0 0; 0.7071 0 0.7071 0; 0.7071 0 0 0.7071')
b = [0.7071067, 0.7071067, 0.7071067, 0.7071067]
d = np.linalg.norm(b)
zKet = np.asmatrix('1;0')
zKet = np.kron(zKet, zKet)
print((U*zKet))
U = U/d
print(np.linalg.norm(U*zKet))
#a = a/np.linalg.norm(a)
U = U
a = a/(10)
z = np.asmatrix('1 0 0 0; 0 1 0 0; 0 0 1 0; 0 0 0 -1')
def calculate_cost(params):
    alpha = params[0]
    alpha2 = params[2]
    alpha3 = params[1]
    alpha4 = params[3]
    Ry1 = np.matrix([[np.cos(alpha/2.), -1*np.sin(alpha/2.)], [np.sin(alpha/2.), np.cos(alpha/2.)]])
    Ry2 = np.matrix([[np.cos(alpha3/2.), -1*np.sin(alpha3/2.)], [np.sin(alpha3/2.), np.cos(alpha3/2.)]])
    Ry = np.kron(Ry1,Ry2)
    Ry3 = np.matrix([[np.cos(alpha2/2.), -1*np.sin(alpha2/2.)], [np.sin(alpha2/2.), np.cos(alpha2/2.)]])
    Ry4 = np.matrix([[np.cos(alpha4/2.), -1*np.sin(alpha4/2.)], [np.sin(alpha4/2.), np.cos(alpha4/2.)]])
    Ry5 = np.kron(Ry3,Ry4)
    V = Ry5*z*Ry

    param1 = 0
    param1 += np.transpose(zKet)@np.transpose(U)@a@V@zKet
    param1 = param1**2
    param2 = 0
    param2 = np.transpose(zKet) * np.transpose(V) * np.transpose(a) * a * V * zKet
    #print("param2 "+str(param2))
    #param2 = np.matmul(np.matmul(np.matmul(np.matmul(np.matmul(np.transpose(zKet),np.transpose(V)),np.transpose(a)),a),V),zKet)
    cost = 1 - (param1/param2)
    cost = np.asarray(cost)
    cost = cost[0][0]
    print("cost = " + str(cost) + " for param1 = " + str(param1) + " for param2 = " + str(param2))
    return abs(cost)
calculate_cost([2, 4.11, 1, 1.57])
out = minimize(calculate_cost, x0=[7, 4, 2, 3], method="COBYLA", options= {'maxiter':20000, 'disp': True}, tol = threshold)
print(out)

[[0.7071]
 [0.7071]
 [0.7071]
 [0.7071]]
0.9999905247680442
cost = 0.3018437399678626 for param1 = [[0.2668461]] for param2 = [[0.38221544]]
cost = 0.07779977173362729 for param1 = [[1.04651044]] for param2 = [[1.13479742]]
cost = 0.14252094768829493 for param1 = [[0.56238238]] for param2 = [[0.65585554]]
cost = 0.06778598928149282 for param1 = [[1.37209749]] for param2 = [[1.47186963]]
cost = 0.11459886017733667 for param1 = [[0.85074188]] for param2 = [[0.96085474]]
cost = 0.12179417089625144 for param1 = [[1.13599652]] for param2 = [[1.29354245]]
cost = 0.0359226637140343 for param1 = [[1.417337]] for param2 = [[1.47014865]]
cost = 0.060175816413520544 for param1 = [[1.11878943]] for param2 = [[1.19042417]]
cost = 0.02907955146290575 for param1 = [[1.30025623]] for param2 = [[1.33919956]]
cost = 0.02015816623521638 for param1 = [[1.13631632]] for param2 = [[1.15969362]]
cost = 0.03653795148973493 for param1 = [[1.12126268]] for param2 = [[1.163785]]
cost = 0.01649071015058079 for pa

cost = 1.8950477511325836e-05 for param1 = [[0.67601329]] for param2 = [[0.6760261]]
cost = 1.8950381177162967e-05 for param1 = [[0.67599897]] for param2 = [[0.67601178]]
cost = 1.895040073296439e-05 for param1 = [[0.67599758]] for param2 = [[0.67601039]]
cost = 1.895038225496748e-05 for param1 = [[0.67599964]] for param2 = [[0.67601245]]
cost = 1.895038936294835e-05 for param1 = [[0.6759905]] for param2 = [[0.67600331]]
cost = 1.895038361088286e-05 for param1 = [[0.67599529]] for param2 = [[0.6760081]]
cost = 1.8950381380000714e-05 for param1 = [[0.67599473]] for param2 = [[0.67600755]]
cost = 1.8950379685689356e-05 for param1 = [[0.67599792]] for param2 = [[0.67601074]]
cost = 1.895038119803516e-05 for param1 = [[0.67599883]] for param2 = [[0.67601164]]
cost = 1.8950377904558557e-05 for param1 = [[0.67599589]] for param2 = [[0.6760087]]
cost = 1.8950379127913308e-05 for param1 = [[0.67599633]] for param2 = [[0.67600914]]
cost = 1.8950379026883013e-05 for param1 = [[0.67599676]] for p